[build-system]
requires = ["setuptools", "wheel", "Cython>=0.29.1, <0.30"]

[tool.setuptools.packages.find]
where = ["chem_formula"]

[tool.setuptools.package-data]
mypkg = ["*.csv", "*.cpp", "*.pyx", "*.pxd"]